### ISSUE TITLE
Function Skeletons

### ISSUE THREAD

**Issue by Scholars-Mate** [Scholars-Mate/Flask-Cards#9]
[In regards to your function skeletons](https://github.com/Scholars-Mate/Flask-Cards/blob/yui/docs/functions.md):

* You titled the file `functions.md`, but did not style with markdown. [Take a look at this guide](https://guides.github.com/features/mastering-markdown/). If you meant to write Python code, use the `.py` extension instead.
* Using a global variable to check if the user is logged in will not work. [We will be using sessions for this](http://flask.pocoo.org/docs/0.12/quickstart/#sessions).

---
```python
#when the program starts
page start()
	if(signedIn)
		return home_page
	else
		return login_page
```
This isn't something our helper functions would be doing. This is what the functions in `flaskcards.py` would be doing. Also keep in mind that Python is not like C or Java. You don't define a return type before the function name.

---
```python
#take user's input, check if we have the user data in out database
page login(str:userName, str:password)
	#call a function to compare the password's hash value, if matched, return true, else return false
	if(compare_hash(userName, password))
		signedIn = true
		return home_page

	else	return login_page
```
Our login function should not be returning a page. It should just return a bool depending on whether the log on was successful or not. If the log in was successful, we should use sessions to indicate whether they are logged in or not. Also, if you are defining types for parameters, they go after the parameter:
```python
from werkzeug.security import check_password_hash
from flask import session

def login(userName: str, password: str) -> bool:
    # SQL query to see is username exists and to retrieve hashed password and userid

    # Verify that hash matches
    if check_password_hash(hashedPassword, password):
        session['userid'] = userid
        return True
    return False
```
Our function in `flaskcards.py` would call this function and depending on the return type, render and return the appropriate page.

---
* The rest of the functions have similar syntax issues, but those aren't a big deal for the skeletons.
* Each function should at the very least be returning a bool so that we know if the operation was a success or failure.
* There is no function/method overloading in Python. [Use default values instead](https://stackoverflow.com/questions/10202938/how-do-i-use-method-overloading-in-python).
* For some of your functions, we aren't getting enough information from the parameters. For instance, in the editCard function, we aren't getting the card id.
* Our helper functions will never create or delete tables, only manipulate data in existing tables.

**Comment by yuichiu416** [comment]
ok, I'll work on that
thanks:D

**Comment by yuichiu416** [comment]
I saw this : 
```python
@app.route("/set/<int:setid>")
def show_set(setid):
    pass
```
in Flask-Cards/flaskcards.py

I guess we should move the data type to the back of the parameter?
Or when they're a route, it's a different story?

**Comment by Scholars-Mate** [comment]
`app.route()` is a method. It can take its parameters however it wants. Notice that what you are giving it is a single string. For Python the language, if you want to give parameter types, they must go after the parameter:
```python
def foo(bar: int) -> int:
    pass
```
By the way, you can style your comments here with markdown. I edited your comment to use markdown, because it makes it much easier to see what is going on. [See this tutorial](https://guides.github.com/features/mastering-markdown/).

**Comment by yuichiu416** [comment]
I think I'll go ahead with correct markdown format rather than python format so that everyone else can read the skeleton easily

**Comment by Scholars-Mate** [comment]
If you are going to use markdown, you won't have to write function skeletons. If we are just writing documentation, we don't care about implementation. Just give the function names, parameters, parameter types, return values, what the function does, etc. I also suggest downloading a markdown viewer so you can see what it will look like before you upload to GitHub.

**Comment by yuichiu416** [comment]
I think the document I was writing should be skeletons, right?

How about I just continue writing it with the markdown style, 
when it's done I can remove the implementation part so that it's easier to read for others

**Comment by Scholars-Mate** [comment]
Whatever works best for you.
